{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2024-02-23T07:17:32.669Z",
    "end": "2024-02-23T07:17:33.277Z",
    "duration": 608,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "f6a63898-788c-4cd6-b81e-df8fb4d4e13d",
      "title": "",
      "fullFile": "cypress\\e2e\\Threat-Generation\\impact.cy.js",
      "file": "cypress\\e2e\\Threat-Generation\\impact.cy.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "An uncaught error was detected outside of a test",
          "fullTitle": "An uncaught error was detected outside of a test",
          "timedOut": null,
          "duration": 416,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": "{\n  \"title\": \"cypress-mochawesome-reporter-screenshots\",\n  \"value\": [\n    [\n      {\n        \"title\": \"Failed screenshot\",\n        \"value\": \"\\\\impact.cy.js\\\\An uncaught error was detected outside of a test (failed).png\"\n      }\n    ]\n  ]\n}",
          "code": "throw err;",
          "err": {
            "message": "TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.runTests is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
            "estack": "TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.runTests is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Suite.eval (webpack://cypress/./cypress/e2e/Threat-Generation/impact.cy.js:140:5)\n    at eval (webpack://cypress/./cypress/e2e/Threat-Generation/impact.cy.js:6:0)\n    at eval (http://localhost:56706/__cypress/tests?p=cypress\\e2e\\Threat-Generation\\impact.cy.js:429:3)\n    at eval (http://localhost:56706/__cypress/tests?p=cypress\\e2e\\Threat-Generation\\impact.cy.js:431:12)\n    at eval (<anonymous>)",
            "diff": null
          },
          "uuid": "07d1a5aa-d09d-4179-9ff9-21177a1dec8d",
          "parentUUID": "f6a63898-788c-4cd6-b81e-df8fb4d4e13d",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "07d1a5aa-d09d-4179-9ff9-21177a1dec8d"
      ],
      "pending": [],
      "skipped": [],
      "duration": 416,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": true,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "6.3.1"
    },
    "marge": {
      "options": {
        "reportDir": "cypress\\reports\\.jsons",
        "overwrite": false,
        "html": false,
        "json": true,
        "timestamp": true,
        "reportTitle": "Vultara Automation Test",
        "showPassed": true,
        "showFailed": true,
        "showPending": true,
        "showSkipped": false,
        "browser": "all",
        "quiet": true
      },
      "version": "5.2.0"
    }
  }
}